//
// Created by Tabbit on 7/17/23.
//

#ifndef COMPETITIVEPROGRAMMING_TEN_KIND_PEOPLE2_H
#define COMPETITIVEPROGRAMMING_TEN_KIND_PEOPLE2_H


class ten_kind_people2 {

};


#endif //COMPETITIVEPROGRAMMING_TEN_KIND_PEOPLE2_H
