//
// Created by Tabbit on 7/16/23.
//

#ifndef COMPETITIVEPROGRAMMING_THREE_DIM_PRINTED_STATUES_H
#define COMPETITIVEPROGRAMMING_THREE_DIM_PRINTED_STATUES_H


class three_dim_printed_statues {

};


#endif //COMPETITIVEPROGRAMMING_THREE_DIM_PRINTED_STATUES_H
