//
// Created by Tabbit on 7/17/23.
//

#ifndef COMPETITIVEPROGRAMMING_TWO_ZERO_FOUR_EIGHT_H
#define COMPETITIVEPROGRAMMING_TWO_ZERO_FOUR_EIGHT_H


class two_zero_four_eight {

};


#endif //COMPETITIVEPROGRAMMING_TWO_ZERO_FOUR_EIGHT_H
